import { Commercial } from './Commercial';
import { LossReason } from './LossReason';
import { Action } from './Action';
import { BusinessType } from './BusinessType';
import { Contact } from './contact';
import { User } from './user';
import { Account } from './accounts';
import { StatusLead } from './StatusLead';
import { Source } from './Source';
export class Lead {
  leadId: number;
  leadCode: string;
  leadComment: string;
  leadDescription: string;
  leadSourceLead: Source;
  leadCreationDate: Date;
  leadUpdateDate: Date;
  leadLedActions: Action[];
  leadLedStatusLead: StatusLead;
  leadAccount: Account;
  leadUsrUser: User;
  leadContact: Contact;
  leadClosingDate: Date;
  leadAmount: number;
  leadNextStep: string;
  leadLossReason: LossReason;
  commercial: Commercial;
  // leadBusinessContributor: BusinessContributor;
  // distributor: Distributor;
  businessType: BusinessType;
  // prerequisites: Prerequisite[];
  statusPrerequisite: string;
  leadRealDuration: number;
  leadEstimatedDuration: number;
  leadTotalDuration: number;
  leadStrRealDuration: string;
  leadStrEstimatedDuration: string;
  leadStrTotalDuration: string;
  leadClientDirect: boolean = true;
}
