import { Byte } from '@angular/compiler/src/util';
import { ProductType } from './ProductType';
import { Image } from 'exceljs';
import { ProductPriceByZone } from './ProductPriceByZone';
export class Product {
  id: number;
  owner: any;
  uomByProductUomSale: any;
  uomByProductUomBase: any;
  uomByProductUomPurshase: any;
  code: string;
  alias: any;
  productParent: Product;
  productType: ProductType[];
  productSubType: any;
  images:any[];
  vat: any;
  materialABCCode: string;
  dlcControl: boolean;
  dluoControl: boolean;
  serialNoControl: boolean;
  lotControl: boolean;
  colorControl: boolean;
  weightControl: boolean;
  coefficient: number;
  productionCost: number;
  salePriceUB: number;
  purshasePriceUB: number;
  raisonToOut: number;
  desc: string;
  shortDesc: string;
  daysOfLife: number;
  active: boolean;
  creationDate: Date;
  updateDate: Date;
  variable1: string;
  variable2: string;
  variable3: string;
  variable4: string;
  variable5: string;
  variable6: string;
  variable7: string;
  variable8: string;
  variable9: string;
  variable10: string;
  qualityOfControl: boolean;
  samplingPercentage: number;
  productPack: any;
  warrantyManagement: boolean;
  discount: number;
  warrantyPeriod: any;
  currency: any;
  currencyPurshase: any;
  productForm: any;
  dimension: boolean;
  //aliases: Alias[];
  //productPacks: ProductPack[];
  //productDimensions: ProductDimension[];
  version: number;
  soldPrice: number;
  warehouse: any;
  stockQuantity: number;
  reservedQuantity: number;
  blockedQuantity: number;
  orderedQuantity: number;
  quantityToReceive: number;
  technicalSheet: string;
  marginOfPurchase: number;
  marginOfCostsOfReturn: number;
  costsOfReturn: number;
  productCategory: any;
  stocked: boolean;
  description: string;
  supplier: any;
  productPriceByZones: ProductPriceByZone[];
  maintenanceCost: number;
}

