import { ProductPack } from './ProductPack';
import { Byte } from '@angular/compiler/src/util';
import { ProductType } from './ProductType';
import { Image } from 'exceljs';
import { ProductPriceByZone } from './ProductPriceByZone';
import { Uom } from './uom';
import { Owner } from './Owner';
import { Vat } from './Vat';
import { Currency } from './Currency';
import { Alias } from './alias';
import { ProductCategory } from './ProductCategory';
import { ProductForm } from './ProductForm';
import { Supplier } from './supplier';
export class Product {
  id: number;
  owner: Owner;
  uomByProductUomSale: Uom;
  uomByProductUomBase: Uom;
  uomByProductUomPurshase: Uom;
  code: string;
  alias: Alias;
  productParent: Product;
  productType: ProductType[];
  productSubType: ProductType;
  images:any[];
  vat: Vat; //tva
  materialABCCode: string;
  dlcControl: boolean;
  dluoControl: boolean;
  serialNoControl: boolean;
  lotControl: boolean;
  colorControl: boolean;
  weightControl: boolean;
  coefficient: number;
  productionCost: number;
  salePriceUB: number;
  purshasePriceUB: number;
  raisonToOut: number;
  desc: string;
  shortDesc: string;
  daysOfLife: number;
  active: boolean;
  creationDate: Date;
  updateDate: Date;
  variable1: string;
  variable2: string;
  variable3: string;
  variable4: string;
  variable5: string;
  variable6: string;
  variable7: string;
  variable8: string;
  variable9: string;
  variable10: string;
  qualityOfControl: boolean;
  samplingPercentage: number;
 // productPack: any;
  warrantyManagement: boolean;
  discount: number; //remis
  warrantyPeriod: any;
  currency: Currency; //devis
  currencyPurshase: Currency; //devis de vente
  productForm: ProductForm;
  dimension: boolean;
  //aliases: Alias[];
  productPacks: ProductPack[];
  //productDimensions: ProductDimension[];
  version: number;
  soldPrice: number;
  warehouse: any;
  stockQuantity: number;
  reservedQuantity: number;
  blockedQuantity: number;
  orderedQuantity: number;
  quantityToReceive: number;
  technicalSheet: string;
  marginOfPurchase: number;
  marginOfCostsOfReturn: number;
  costsOfReturn: number;
  productCategory: ProductCategory;
  stocked: boolean;
  description: string;
  supplier: Supplier;
  productPriceByZones: ProductPriceByZone[];
  maintenanceCost: number;
}

